language: php
php:
  - '7.2'
  - nightly
matrix:
  allow_failures:
    - nightly
install: composer install -o --no-interaction
script: vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-clover=coverage.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)
